JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	BoyerMoore.java \
    LCS.java \
    Levenshtein.java \
	Main.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class
	$(RM) out/BoyerMoore/*.out
	$(RM) out/Levenshtein/*.out
	$(RM) out/LCS/*.out
run:
	java Main